ViewModels/VideoViewModel.cs
using Kalikoe_BAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Kalikoe.ViewModels
{
    public class VideoViewModel
    {
        public List<Videos> listVideosVM { get; set; }
        public List<LeaderBoard> leaderVM { get; set; }
        public List<Videocomments> commentVM { get; set; }
        public Videos videoVM { get; set; }
        public Challenge chVM { get; set; }
        public List<challengelist> chListVM { get; set; }
    }

}

Controllers/VideoController.cs
using Kalikoe.ViewModels;
using Kalikoe_BAL;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace Kalikoe.Controllers
{

    public class VideoController : Controller
    {
        CRUDVideos objCRUD = new CRUDVideos();
        // GET: Video
        public ActionResult UploadVideos()
        {
            if (Session["userid"] != null)
            {
                SeoDetails seo = new SeoDetails();
                seo = objCRUD.GetSeoDetails("4");
                ViewBag.pagetitle = seo.pagetitle;
                ViewBag.metadesc = seo.pagedescription;
                return View("UploadVideos");
            }
            else
            {
                return Redirect("/login");
            }
        }
        public ActionResult privacypolicy()
        {
            SeoDetails seo = new SeoDetails();
            seo = objCRUD.GetSeoDetails("9");
            ViewBag.pagetitle = seo.pagetitle;
            ViewBag.metadesc = seo.pagedescription;
            return View("privacypolicy");
        }
        public ActionResult termsandconditions()
        {
            SeoDetails seo = new SeoDetails();
            seo = objCRUD.GetSeoDetails("8");
            ViewBag.pagetitle = seo.pagetitle;
            ViewBag.metadesc = seo.pagedescription;
            return View("termsandconditions");
        }
        public ActionResult disclaimer()
        {
            SeoDetails seo = new SeoDetails();
            seo = objCRUD.GetSeoDetails("10");
            ViewBag.pagetitle = seo.pagetitle;
            ViewBag.metadesc = seo.pagedescription;
            return View("disclaimer");
        }
        public ActionResult thankyou()
        {
            return View("thankyou");
        }
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult UploadVideos(Videos videoVM, HttpPostedFileBase file1)
        {
            if (Session["userid"] != null)
            {
                string strUploadType = "embed";
                videoVM.access = "1";
                videoVM.categoryid = "1";
                videoVM.embedcode = "";
                if (videoVM.description == null)
                {
                    videoVM.description = "";
                }

                if (file1 != null)
                {
                    string strPath = "";
                    string imgurl = string.Empty;
                    string pic = System.IO.Path.GetFileName(file1.FileName);
                    if (objCRUD.Isimage(pic) == true)
                    {
                        strPath = "/image-content/";
                        strUploadType = "image";
                    }
                    else
                    {
                        strPath = "/Videos/";
                        strUploadType = "manual";
                    }
                    strPath = strPath + pic;
                    file1.SaveAs(ConfigurationManager.AppSettings["websitefolderpath"] + strPath);
                    videoVM.videourl = strPath;

                }
                videoVM.uploadtype = strUploadType;
                videoVM.userid = Session["userid"].ToString();
                string strRet = objCRUD.InsertVideos(videoVM);
                ViewBag.success = "Yes";
                return View("UploadVideos");
            }
            else
            {
                return Redirect("/login");
            }

        }

        public ActionResult VideoList()
        {

            VideoViewModel videoVM = new VideoViewModel();
            videoVM.listVideosVM = objCRUD.GetAllUserVideos();
            return View("VideoList", videoVM);
        }

        public ActionResult LeaderBoard()
        {
            SeoDetails seo = new SeoDetails();
            seo = objCRUD.GetSeoDetails("2");
            ViewBag.pagetitle = seo.pagetitle;
            ViewBag.metadesc = seo.pagedescription;
            VideoViewModel videoVM = new VideoViewModel();
            videoVM.leaderVM = objCRUD.GetLeaderBoard();
            return View("leaderboard", videoVM);
        }

        public ActionResult Dashboard()
        {
            if (Session["userid"] != null)
            {
                VideoViewModel videoVM = new VideoViewModel();
                videoVM.listVideosVM = objCRUD.Dashboard(Session["userid"].ToString());
                if (Request.QueryString["type"] != null)
                {
                    if (Request.QueryString["type"].ToString() == "first")
                    {
                        ViewBag.showslide = "Yes";
                    }
                    else
                    {
                        ViewBag.showslide = "No";
                    }
                }
                else
                {
                    ViewBag.showslide = "No";
                }
                SeoDetails seo = new SeoDetails();
                seo = objCRUD.GetSeoDetails("3");
                ViewBag.pagetitle = seo.pagetitle;
                ViewBag.metadesc = seo.pagedescription;
                return View("dashboard", videoVM);
            }
            else
            {
                return Redirect("/login");
            }
        }



        [HttpPost]
        public JsonResult fnLike(updatelikemodel lkVM)
        {
            if (Session["userid"] != null)
            {
                if (lkVM.type == "like")
                {
                    string strRet = objCRUD.InsertLikes(Session["userid"].ToString(), lkVM.vid);
                }
                else if (lkVM.type == "unlike")
                {
                    string strRet = objCRUD.DeleteLikes(Session["userid"].ToString(), lkVM.vid);
                }
                return Json("N", JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json("E", JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult challengeUpdate(challengestatus chVM)
        {
            string strRet = objCRUD.UpdateChallengeStatus(chVM.challengeid, chVM.status);
            return Json("N", JsonRequestBehavior.AllowGet);
        }

        public ActionResult Sponsor(Sponsor spVM)
        {
            if (Session["userid"] != null)
            {
                spVM.vid = Request.Form["hdnkali"];
                spVM.kaliamount = Request.Form["hdnkaliamt"];
                string strRet = objCRUD.Sponsor(spVM);
                return Redirect(this.Request.UrlReferrer.PathAndQuery + "#category");
            }
            else
            {
                return Redirect("/login");
            }
        }
        public ActionResult fnRateIt(RateIt rtVM)
        {
            if (Session["userid"] != null)
            {
                rtVM.vid = Request.Form["hdnvid"];
                rtVM.rating = Request.Form["hdnrating"];
                rtVM.userid = Session["userid"].ToString();
                string strRet = objCRUD.InsertRateIt(rtVM.userid, rtVM.vid, rtVM.rating);
                return Redirect(this.Request.UrlReferrer.PathAndQuery + "#category");
            }
            else
            {
                return Redirect("/login");
            }
        }
        public ActionResult Comment()
        {
            string strRet = objCRUD.InsertComments(Request.Form["txtComment"], Request.Form["hdnvid"], Session["userid"].ToString());
            string s1 = this.Request.UrlReferrer.PathAndQuery;
            string s2 = Request.Path.ToString();
            return Redirect(this.Request.UrlReferrer.PathAndQuery + "#comment");
        }
        public ActionResult VideoDetails(string id)
        {
            string strVid = id.Split('-').Last();
            VideoViewModel videoVM = new VideoViewModel();
            string strUserId = "0";
            if (Session["userid"] != null)
            {
                strUserId = Session["userid"].ToString();
            }
            videoVM.videoVM = objCRUD.VideoDetails(strVid, strUserId);
            videoVM.commentVM = objCRUD.GetComments(strVid);
            ViewBag.vid = strVid;
            ViewBag.pagetitle = videoVM.videoVM.displayname;
            ViewBag.metadesc = videoVM.videoVM.displayname;
            return View("videodetails", videoVM);
        }
        public ActionResult ChallengeList()
        {
            if (Session["userid"] != null)
            {
                VideoViewModel videoVM = new VideoViewModel();
                videoVM.chListVM = objCRUD.GetChallengeList(Session["userid"].ToString());
                SeoDetails seo = new SeoDetails();
                seo = objCRUD.GetSeoDetails("11");
                ViewBag.pagetitle = seo.pagetitle;
                ViewBag.metadesc = seo.pagedescription;
                return View("challengelist", videoVM);
            }
            else
            {
                return Redirect("/login");
            }

        }
        public ActionResult MyChallengeList()
        {
            if (Session["userid"] != null)
            {
                VideoViewModel videoVM = new VideoViewModel();
                videoVM.chListVM = objCRUD.GetMyChallengeList(Session["userid"].ToString());
                SeoDetails seo = new SeoDetails();
                seo = objCRUD.GetSeoDetails("11");
                ViewBag.pagetitle = seo.pagetitle;
                ViewBag.metadesc = seo.pagedescription;
                return View("challengelist", videoVM);
            }
            else
            {
                return Redirect("/login");
            }
        }
        [ValidateInput(false)]
        [HttpPost]

Views/Video/Challengethankyou.cshtml
@{
    Layout = "~/Views/Home/KalikoeMaster1.cshtml";
}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Kalikoe</title>

    <!-- Favicon -->
    <link rel="icon" href="images/favicon.png" type="image/png" />

    <!--Bootstrap and Other Vendors-->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="css/magnific-popup.css">
    <link rel="stylesheet" href="vendors/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="vendors/bootstrap-select/css/bootstrap-select.min.css" media="screen">

    <!--Fonts-->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>

    <!--Theme Styles-->
    <link rel="stylesheet" href="css/default/style.css">
    <link rel="stylesheet" href="css/responsive/responsive.css">

    <!--[if lt IE 9]>
      <script src="js/html5shiv.min.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->

</head>
<body class="home">

    <section class="row upload_media">
        <div class="container">
            <div class="row">
                <h2 style="color:white;padding-top:120px;">Thank you.</h2>
            </div>
        </div>
    </section> <!--Upload Form-->
    <!-- Preloader -->
    <div id="preloader">
        <div id="status">&nbsp;</div>
    </div>

    <!--jQuery, Bootstrap and other vendor JS-->
    <!--jQuery-->
    <script src="js/jquery-3.2.1.min.js"></script>

    <!--Bootstrap JS-->
    <script src="js/bootstrap.min.js"></script>

    <!--jScroll-->
    <script src="js/jquery.jscroll.min.js"></script>

    <!--Magnific Popup-->
    <script src="js/jquery.magnific-popup.min.js"></script>

    <!--Bootstrap Select-->
    <script src="vendors/bootstrap-select/js/bootstrap-select.min.js"></script>

    <!--Theme JS-->
    <script src="js/theme.js"></script>
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" />
    <script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
    <script>
        window.addEventListener("load", function () {
            window.cookieconsent.initialise({
                "palette": {
                    "popup": {
                        "background": "#000"
                    },
                    "button": {
                        "background": "#670BB7"
                    }
                },
                "content": {
                    "href": "http://40.71.179.31/privacy-and-policy"
                }
            })
        });
    </script>
    <div id="dvPopup" class="simplePopup1" style="background-color:white;left:0px !important;color:black !important;overflow: scroll;height:80%;">
        http://40.71.179.31/signup?refer=@Session["encemailaddress"].ToString()
    </div>
    <script>
        function fnPopRefer() {
            $('#dvPopup').simplePopup({
                centerPopup: true,
                open: function () { },
                closed: function () { }
            });
        }
    </script>

    <style>
        .load-full-screen {
            margin-top: -11px;
        }

        .simplePopup {
            display: none;
            position: fixed !important;
            z-index: 3;
            color: #fff;
            padding: 8px;
            width: 30%;
            min-width: 30%;
            padding: 3%;
        }

        .simplePopup1 {
            display: none;
            position: fixed !important;
            z-index: 3;
            color: #fff;
            padding: 8px;
            width: 45%;
            min-width: 45%;
            padding: 3%;
            top: 20% !important;
            border-radius: 10%;
        }

        .simplePopupClose {
            float: right;
            font-weight: bold;
        }

        .simplePopupBackground {
            display: none;
            background: #000;
            position: fixed !important;
            height: 100%;
            width: 100%;
            top: 0;
            left: 0;
            z-index: 1;
        }
    </style>

    <script src="/js/popup.js"></script>
</body>
<!-- Mirrored from uxart.io/downloads/metavideo-html/ by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 24 Jan 2019 06:53:39 GMT -->
</html>

Views/Video/UploadVideos.cshtml
@model Kalikoe.ViewModels.VideoViewModel
@{
    Layout = "~/Views/Home/KalikoeMaster1.cshtml";
}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Kalikoe</title>

    <!-- Favicon -->
    <link rel="icon" href="images/favicon.png" type="image/png" />

    <!--Bootstrap and Other Vendors-->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="css/magnific-popup.css">
    <link rel="stylesheet" href="vendors/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="vendors/bootstrap-select/css/bootstrap-select.min.css" media="screen">

    <!--Fonts-->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>

    <!--Theme Styles-->
    <link rel="stylesheet" href="css/default/style.css">
    <link rel="stylesheet" href="css/responsive/responsive.css">

    <!--[if lt IE 9]>
      <script src="js/html5shiv.min.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->

</head>
<body class="home">
    <section class="row" style="background-color:white">

        <div class="row media-grid content_video_posts">
            @using (Html.BeginForm("UploadVideos", "Video", FormMethod.Post, new { style = "width:95%", @class = "container-fluid signup_form auth_form", enctype = "multipart/form-data" }))
            {
                <div class="form-inner row">
                    <div class="form-header row m0">
                        <h4>Upload Video/Image</h4>
                    </div>
                    <div class="form-body row m0">
                        @Html.TextBoxFor(m => m.videoVM.title, new { @class = "form-control", @placeholder = "Title", @required = "true", @style = "width:92%" })<br />
                        @Html.TextBoxFor(m => m.videoVM.videourl, new { @class = "form-control", @placeholder = "Video Url", @style = "width:92%" })<br />
                        <span style="font-size:12px">(supported website:dailymotion.com,vimeo.com and youtube.com)</span><br /><br />
                        Or Upload Image/Video <br /><br />
                        <input type="file" class="form-control" name="file1" width="200px" placeholder="Thumbnail(Optional)" /><br />
                        @Html.TextAreaFor(m => m.videoVM.description, new { @class = "form-control", @placeholder = "Description", @required = "true", @cols = "40", @rows = "5" })            <br />
                        @Html.TextBoxFor(m => m.videoVM.tags, new { @class = "form-control", @placeholder = "Tags", @required = "true", @style = "width:92%" })

                        <input type="submit" value="Upload" class="btn btn-default form-control">
                    </div>
                   
                </div>
            }
        </div>
    </section>


    <!-- Preloader -->
    <div id="preloader">
        <div id="status">&nbsp;</div>
    </div>

    <!--jQuery, Bootstrap and other vendor JS-->
    <!--jQuery-->
    @*<script src="js/jquery-3.2.1.min.js"></script>*@

    <!--Bootstrap JS-->
    @*<script src="js/bootstrap.min.js"></script>*@

    <!--jScroll-->
    <script src="js/jquery.jscroll.min.js"></script>

    <!--Magnific Popup-->
    <script src="js/jquery.magnific-popup.min.js"></script>

    <!--Bootstrap Select-->
    <script src="vendors/bootstrap-select/js/bootstrap-select.min.js"></script>

    <!--Theme JS-->
    <script src="js/theme.js"></script>
    <style>
        .signup_form .form-inner {
            width: 500px !important;
            margin-top: 20px !important;
        }

        .auth_form {
            height: auto !important;
        }
    </style>
    <script src="https://cdn.ckeditor.com/4.10.0/standard/ckeditor.js"></script>
    <script>
        CKEDITOR.replace($("#videoVM_description").attr("name"));
    </script>
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" />
    <script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
    <script src="/js/popup.js"></script>
    <div id="dvPopup" class="simplePopup1" style="background-color:white;left:0px !important;color:black !important;overflow: scroll;height:80%;">
        @if (Session["userid"] != null)
        {<textarea cols="70" rows="4">http://kali-tv/signup?refer=@Session["encemailaddress"].ToString()</textarea>}
    </div>
    <script>
        function fnPopRefer() {
            $('#dvPopup').simplePopup({
                centerPopup: true,
                open: function () { },
                closed: function () { }
            });
        }
    </script>

    <style>
        .load-full-screen {
            margin-top: -11px;
        }

        .simplePopup {
            display: none;
            position: fixed !important;
            z-index: 3;
            color: #fff;
            padding: 8px;
            width: 30%;
            min-width: 30%;
            padding: 3%;
        }

        .simplePopup1 {
            display: none;
            position: fixed !important;
            z-index: 3;
            color: #fff;
            padding: 8px;
            width: 45%;
            min-width: 45%;
            padding: 3%;
            top: 20% !important;
 
        }

        .simplePopupClose {
            float: right;
            font-weight: bold;
        }

        .simplePopupBackground {
            display: none;
            background: #000;
            position: fixed !important;
            height: 100%;
            width: 100%;
            top: 0;
            left: 0;
            z-index: 1;
        }
    </style>
    @if (ViewBag.success != null)
    {
        <script type='text/javascript'>
            $(document).ready(function () {
                $('#dvThankyou').simplePopup({
                    centerPopup: true,
                    open: function () { },
                    closed: function () { }
                });
            });
        </script>
    }
    <div id="dvThankyou" class="simplePopup1" style="background-color:white;left:0px !important;color:black !important;overflow: scroll;height:60%;">
        <div style="padding: 28% 0% 0 0%;"><span style="color:#FF8E52;font-weight:bold;font-size:25px;text-align: center;">Thank you for uploading video/image.</span></div>
    </div>
</body>
<!-- Mirrored from uxart.io/downloads/metavideo-html/ by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 24 Jan 2019 06:53:39 GMT -->
</html>

Views/Video/VideoList.cshtml
@model Kalikoe.ViewModels.VideoViewModel
@{
    Layout = "~/Views/Home/KalikoeMaster1.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<!-- Mirrored from uxart.io/downloads/metavideo-html/category.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 24 Jan 2019 06:54:17 GMT -->
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Kalikoe</title>

    <!-- Favicon -->
    <link rel="icon" href="images/favicon.png" type="image/png" />

    <!--Bootstrap and Other Vendors-->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="css/magnific-popup.css">
    <link rel="stylesheet" href="vendors/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="vendors/bootstrap-select/css/bootstrap-select.min.css" media="screen">

    <!--Fonts-->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>

    <!--Theme Styles-->
    <link rel="stylesheet" href="css/default/style.css">
    <link rel="stylesheet" href="css/responsive/responsive.css">

    <!--[if lt IE 9]>
      <script src="js/html5shiv.min.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->

</head>
<body class="home">

   

<section class="row recent_uploads">
    <div class="container">
        <div class="row media-grid content_video_posts">
            @if (Model.listVideosVM != null && Model.listVideosVM.Count > 0)
            {
                for (int i = 0; i <= Model.listVideosVM.Count - 1; i++)
                {
                    <article class="col-sm-3 video_post postType3">
                        <div class="inner row m0">
                            <a href="single-video.html">
                                <div class="row screencast m0">
                                    <iframe width="285" height="210" class="cast img-responsive"
                                            src="@Model.listVideosVM[i].videourl"></iframe>
                                    <div class="play_btn"></div>
                                </div>
                            </a>
                            <div class="row m0 post_data">
                                <div class="category"><a href="category.html"><img src="images/icons/catagory.png" alt="">@Model.listVideosVM[i].tags</a></div>
                                <div class="row m0"><a href="single-video.html" class="post_title">@Model.listVideosVM[i].title</a></div>
                                <div class="fleft date">Published: @Model.listVideosVM[i].publishedon</div>
                                <div class="fright views"><a href="#"><img src="images/icons/views.png" alt=""></a></div>
                            </div>
                        </div>
                    </article>
                }
            }
            <div class="row m0">
                <div class="clearfix"></div>
                <a href="inc/more-uploads-1.html" class="load_more_videos">Load more videos</a>
            </div>
        </div>
    </div>
</section> <!--Recent Upload-->


<!-- Preloader -->
<div id="preloader">
    <div id="status">&nbsp;</div>
</div>

<!--jQuery, Bootstrap and other vendor JS-->
<!--jQuery-->

<!--Bootstrap JS-->
<script src="js/bootstrap.min.js"></script>

<!--Dropzone-->
<script src="js/dropzone.html"></script>

<!--jScroll-->
<script src="js/jquery.jscroll.min.js"></script>

<!--Magnific Popup-->
<script src="js/jquery.magnific-popup.min.js"></script>

<!--Bootstrap Select-->
<script src="vendors/bootstrap-select/js/bootstrap-select.min.js"></script>

<!--Theme JS-->
<script src="js/theme.js"></script>
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" />
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
<script src="/js/popup.js"></script>
<div id="dvPopup" class="simplePopup1" style="background-color:white;left:0px !important;color:black !important;overflow: scroll;height:60%;">
    <br />
    <b>GET FREE KALI DOLLARS<br/>(limited time sticker)<br/>Invite your friends with this custom link and you will earn KDC for every user that signs up</b><br />
    @if (Session["userid"] != null)
    {<textarea cols="70" rows="4">http://kali-tv/signup?refer=@Session["encemailaddress"].ToString()</textarea>}
</div>
<script>
    function fnPopRefer() {
        $('#dvPopup').simplePopup({
            centerPopup: true,
            open: function () { },
            closed: function () { }
        });
    }
</script>

<style>
    .load-full-screen {
        margin-top: -11px;
    }

    .simplePopup {
        display: none;
        position: fixed !important;
        z-index: 3;
        color: #fff;
        padding: 8px;
        width: 30%;
        min-width: 30%;
        padding: 3%;
    }

    .simplePopup1 {
        display: none;
        position: fixed !important;
        z-index: 3;
        color: #fff;
        padding: 8px;
        width: 45%;
        min-width: 45%;
        padding: 3%;
        top: 20% !important;
        border-radius: 10%;
    }

    .simplePopupClose {
        float: right;
        font-weight: bold;
    }

    .simplePopupBackground {
        display: none;
        background: #000;
        position: fixed !important;
        height: 100%;
        width: 100%;
        top: 0;
        left: 0;
        z-index: 1;
    }
</style>
</body>
<!-- Mirrored from uxart.io/downloads/metavideo-html/category.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 24 Jan 2019 06:54:20 GMT -->
</html>

Views/Video/thankyou.cshtml
@{
    Layout = "~/Views/Home/KalikoeMaster1.cshtml";
}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Kalikoe</title>

    <!-- Favicon -->
    <link rel="icon" href="images/favicon.png" type="image/png" />

    <!--Bootstrap and Other Vendors-->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="css/magnific-popup.css">
    <link rel="stylesheet" href="vendors/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="vendors/bootstrap-select/css/bootstrap-select.min.css" media="screen">

    <!--Fonts-->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>

    <!--Theme Styles-->
    <link rel="stylesheet" href="css/default/style.css">
    <link rel="stylesheet" href="css/responsive/responsive.css">

    <!--[if lt IE 9]>
      <script src="js/html5shiv.min.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->

</head>
<body class="home">
       <section class="row upload_media">
        <div class="container">
            <div class="row">
                <h2 style="color:white;padding-top:120px;">Your video details has been added successfully.<br />Thank you.</h2>
            </div>
        </div>
    </section> <!--Upload Form-->

    
    <!-- Preloader -->
    <div id="preloader">
        <div id="status">&nbsp;</div>
    </div>

    <!--jQuery, Bootstrap and other vendor JS-->
    <!--jQuery-->
    <script src="js/jquery-3.2.1.min.js"></script>

    <!--Bootstrap JS-->
    <script src="js/bootstrap.min.js"></script>

    <!--jScroll-->
    <script src="js/jquery.jscroll.min.js"></script>

    <!--Magnific Popup-->
    <script src="js/jquery.magnific-popup.min.js"></script>

    <!--Bootstrap Select-->
    <script src="vendors/bootstrap-select/js/bootstrap-select.min.js"></script>

    <!--Theme JS-->
    <script src="js/theme.js"></script>
    <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" />
    <script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
</body>
<!-- Mirrored from uxart.io/downloads/metavideo-html/ by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 24 Jan 2019 06:53:39 GMT -->
</html>